apiVersion: apps/v1
kind: Deployment
metadata:
  name: 08srujan
  labels:
    app: 08srujan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 08srujan
  template:
    metadata:
      labels:
        app: 08srujan
    spec:
      containers:
      - name: 08srujan
        image: sruju07/labtest:latest
        ports:
        - containerPort: 80
