apiVersion: v1
kind: Service
metadata:
  labels:
    app: 221058008_srujan
  name: 221058008_srujan
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: 221058008_srujan
